kind: MCPTools
apiVersion: api.ibm.com/v1
metadata:
  name: pet-mcp-tool-mjsdo
  namespace: pet-mcp
  version: 1.0.27
  tags: []
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.


    Some useful links:

    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
spec:
  tools:
    - name: get_pet_by_id
      description: This tool retrieves a specific pet using the unique ID. It provides
        detailed information about the pet, ensuring users can access individual
        pet records easily.
      inputSchema:
        type: object
        properties:
          petId:
            description: ID of the pet to return (e.g., 12345).
            x-parameter-location: path
            type: integer
            format: int64
        required:
          - petId
      title: Find pet by ID.
      x-api-binding:
        operationPath: /pet/{petId}
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: get_store_inventory
      description: This tool retrieves an inventory map of status codes and
        corresponding quantities. It gives users insight into available stock,
        aiding in operations and decision-making processes.
      inputSchema:
        type: object
        properties: {}
      title: Returns pet inventories by status.
      x-api-binding:
        operationPath: /store/inventory
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
