kind: MCPTools
apiVersion: api.ibm.com/v1
metadata:
  name: pet-mcp-tool-mjsdo
  namespace: pet-mcp
  version: 1.0.27
  tags: []
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.


    Some useful links:

    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
spec:
  tools:
    - name: get_pet_status
      description: This tool searches for pets based on specific status values
        provided in a comma-separated string. It allows users to retrieve pets
        according to their status within the pet store system.
      inputSchema:
        type: object
        properties:
          status:
            description: The status value to filter pets by (e.g., available, pending,
              sold).
            x-parameter-location: query
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
        required:
          - status
      title: Finds Pets by status.
      x-api-binding:
        operationPath: /pet/findByStatus
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: get_pet_tags
      description: This tool finds pets with assigned tags. It enables users to filter
        pets by multiple tag names, allowing for more precise and tailored
        search results.
      inputSchema:
        type: object
        properties:
          tags:
            description: An array of tags to filter pets by (e.g., ['fluffy', 'dog']).
            x-parameter-location: query
            type: array
            items:
              type: string
        required:
          - tags
      title: Finds Pets by tags.
      x-api-binding:
        operationPath: /pet/findByTags
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
