apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoxd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Holajuwon/argoxd.git
    targetRevision: HEAD
    path: charts/argoxd
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argoxd-standalone
      namespace: default
      jsonPointers:
        - /data/STANDALONE_PASSWORD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
