apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argoxd.fullname" . }}-scripts
  labels:
    {{- include "argoxd.labels" . | nindent 4 }}
data:
  apic-build-and-post.sh: |
{{ .Files.Get "files/apic-build-and-post.sh" | indent 4 }}
