apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "argoxd.fullname" . }}-sync-job
  labels:
    {{- include "argoxd.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "argoxd.selectorLabels" . | nindent 8 }}
        job: sync
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      containers:
        - name: apic-build-and-post
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - /scripts/apic-build-and-post.sh
          env:
            - name: WORK_DIR
              value: /work
            - name: ARGOXD_ENDPOINT
              value: "http://$(ARGOXD_SERVICE_HOST):$(ARGOXD_SERVICE_PORT_HTTP)"
          envFrom:
            - secretRef:
                name: {{ include "argoxd.fullname" . }}-standalone
            - secretRef:
                name: argoxd-standalone-credentials
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: work-files
              mountPath: /work
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: work-files
          configMap:
            name: {{ include "argoxd.fullname" . }}-work-files
        - name: scripts
          configMap:
            name: {{ include "argoxd.fullname" . }}-scripts
