apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - sync-job.yaml

configMapGenerator:
  - name: argoxd-work-files
    files:
      - .apistudio-projects
      - pet-mcp/invoke-mjsdo.yaml
      - pet-mcp/pet-mcp-freeflowpolicysequence-mjsdo.yaml
      - pet-mcp/pet-mcp-plan-mjsdo.yaml
      - pet-mcp/pet-mcp-plan-x-mjsdo.yaml
      - pet-mcp/pet-mcp-quota-mjsdo.yaml
      - pet-mcp/pet-mcp-quota-x-mjsdo.yaml
      - pet-mcp/pet-mcp-server-mjsdo.yaml
      - pet-mcp/pet-mcp-tool-mjsdo.yaml
      - pet-mcp/pet-spec.yml
      - pet-mcp/telemetry-mjsdo.yaml
    options:
      disableNameSuffixHash: true
