apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

configMapGenerator:
  - name: argoxd-work-files
    files:
      - invoke-mjsdo.yaml
      - pet-mcp-freeflowpolicysequence-mjsdo.yaml
      - pet-mcp-plan-mjsdo.yaml
      - pet-mcp-plan-x-mjsdo.yaml
      - pet-mcp-quota-mjsdo.yaml
      - pet-mcp-quota-x-mjsdo.yaml
      - pet-mcp-server-mjsdo.yaml
      - pet-mcp-tool-mjsdo.yaml
      - pet-spec.yml
      - telemetry-mjsdo.yaml
    options:
      disableNameSuffixHash: true
